name: simple_workflow
on: [push]
jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: hello world
              run: echo "Hello World"
            - name: multi-line command
              run: |
                echo "This is a multi-line command"
                echo "This is the second line"
    job2:
        name: Job 2 tesst
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo "hello world"
    job3:
        name: Job 3 tesst
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo "hello world"