name: simple_workflow
on: workflow_dispatch
jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: hello world
              run: echo "Hello World"
            - name: multi-line command
              run: |
                echo "This is a multi-line command"
                echo "This is the second line"
